### ISSUE TITLE
라우팅 구성

### ISSUE THREAD

**Issue by jun094** [OPGG-HACKTHON/Web-A-Front#14]
## Steps 🔍

- [x] pages 폴더 내에 파일 구성
- [x] about페이지 Dynamic Routes 생성
- [x] ~~abuout 페이지 `GetServerSideProps` 생성~~
- [x] abuout 페이지 `getInitialProps ` 생성
- [x] Error 페이지 커스텀 (404, 500)

## Description 📝
Next.js 로 라우팅 구성

**Comment by Sh031224** [comment]
지금 인프라에 Lambda 함수 오류 (Serverless component 라이브러리 오류)로 `getServerSideProps` 를 작성시 503 에러가 발생하는 경우가 있어, `getInitialProps` 로 대체해주시면 감사하겠습니다!

**Comment by jun094** [comment]
> 지금 인프라에 Lambda 함수 오류 (Serverless component 라이브러리 오류)로 `getServerSideProps` 를 작성시 503 에러가 발생하는 경우가 있어, `getInitialProps` 로 대체해주시면 감사하겠습니다!

네넵 ! 확인했습니다 :)
